Historically, the Word application (technically speaking a Word instance) is required to create, print or edit a Word document in it. 
This applies to both the user and the developer.

But this is becoming an obstacle:
- Since the Word application was primarily designed for the user, it is more difficult to use it in a server environment. 
However, more and more services are being performed by server applications, which is increasingly restricting the timeliness and usefulness of conventional Word documents.
- The programming interfaces are comparatively slow - especially when Word is controlled from the outside; not least because the preview is updated continuously. 
In addition, the remote control has to work through several COM interfaces, which further slows down the execution.
- Documents are increasingly no longer archived in paper form, but digitally. 
The old, proprietary binary file formats are poorly suited for this.
- And finally, the spirit of the times calls for open standards and files that are not reserved for non-proprietary software. A new file format for core office applications was required.

The result was introduced in Office 2007: Office Open XML. It replaces the previously used binary file formats. 
This chapter provides an introduction to the structure of Open XML documents and how to use them. 
Unfortunately, the VBA developer has no tailored tools to work with the new file format. 
Nevertheless, this chapter is intended to serve as a basis for understanding the new structures.

TIP: Some document damage problems can be solved by manually intervening in the XML files based on the document!

In the next chapter, we present a tool that takes over the structure management described in this chapter, so that the developer can concentrate on working with the document content. 
However, basic knowledge of the structure and interrelationships of the file format are also essential for this.

== The Open XML file format

An Open XML file consists of a ZIP package of numerous XML files that can be created and manipulated using conventional tools. 
The underlying schemes are publicly accessible and have been approved by the ISO (International Organization for Standardization) and the ECMA as Open Packaging Conventions (OPC) standards.

NOTE:Standardization of file formats
+
The Open Packaging Conventions (OPC) were originally part of the Office Open XML file formats, which were standardized by the ECMA in 2006 as »ECMA-376«. 
This standard is also known as »ECMA-376 1st edition (2006)«.
+
A new version of the standard was approved by the ISO in 2008 as "ISO/IEC-29500:2008". 
An updated version of the ECMA standard, which was technologically based on the ISO standard, was published as »ECMA-376 2nd edition (2008)«.
+
A third version of the ECMA standard was published in June 2011, bringing the information in line with the ISO standard for Office 2010.

The four main documents of the ISO standard cover around 7,000 pages. 
The standard defines »transitional« provisions, so that documents that follow the previous standard are considered valid transitional documents of the ISO standard. 
It is envisaged that the transitional provisions will be removed later, which would correspond to the strict ISO standard ("Strict").

The Office 2007 and Mac 2008 applications (Word, Excel and PowerPoint) create and recognize documents that meet the standard »ECMA-376 1st edition (2006)«. 
Office 2010 and Mac 2011 application documents are more in line with the ISO standard. 
Word 2010 can read "Strict" format documents, but only write the "Transitional" format.

Office 2013 supports reading and writing the »Transitional« format as well as the ISO »Strict« format, which does not include the »Legacy« functionality. 
You can find more information on this at http://blogs.msdn.com/b/dmahugh/archive?/2010/04/06/office-s-support-for-iso-iec-29500-strict.aspx

In addition to public accessibility, the Open XML file format has other advantages - especially for programmers whose code does not run in the VBA environment (which means that Word can be controlled remotely):

- A Word document can be created and edited in a server environment and without the presence of the Word application. 
Word documents can even be created and edited on systems on which no Microsoft software is used or Office cannot be run at all, such as Linux/UNIX.
- The sequence of actions is very fast compared to controlling Word applications using the object model
- Splitting off the content management from the user interface makes it possible to align the applications and their remote control options more closely with the users and the expansion of the user interface. 
From the outside, the office applications are increasingly sealed off - which is to be welcomed for security reasons - and withdrawn from the general developer.

NOTE: When a solution based on the Office Open XML format is not optimal? 
This is the case if it requires functionality that is only provided by the user interface. 
Examples include converting a file to another file format and updating dynamic content such as field functions (including tables of contents and page numbering). 
In this case, the document must still be opened and saved in the Word application. 
For the server environment, the »Word Automation Services« are available, which are part of Microsoft SharePoint from version 2010 (see also http://msdn.microsoft.com/de-de/library/ee558830(v=office.14).aspx [Ms472-K22-02]).

Before you can use Open XML, you need to understand the basics of the file format. 
Only with this knowledge a meaningful work with the Open XML file format is possible.

Stay open to new things: Working with Office Open XML and the tools developed for it reflect the principles of XML rather than the object-oriented philosophies we are familiar with.

The Word document Bsp22_01.docx serves as the first example for this discussion, the content of which is shown in Figure 22.1.

image::22.1 A Word Document

ONLINE: The example file Bsp22_01.docx is located in the download archive for the book in the \Examples\Kap22 folder.

== The components of an Open XML file

First we will look at the structure and components of a Word Open XML file. 
You can convince yourself of the accessibility of the Open XML file format without having a developer interface at hand. 
Open Windows Explorer, navigate to the sample file Bsp22_01.docx and mark the entry.

NOTE: Files of the new file format are clearly recognizable by the file extension, because they consist of four characters: docx, docm, dotx, dotm. 
The file has the extension .doc or .dot, there is a file in the old, binary format that cannot be viewed without the Word application.

Press the (F2) key, move the insertion point behind the file extension and enter .zip as the new file extension (see Figure 22.2). 
Complete the entry with the kbd:[Enter] and confirm the Windows security prompt with OK.

The file is then displayed as a ZIP folder in Windows Explorer and can be treated like a normal folder. 
For example, you can browse through its subfolders to see how the Open XML file is structured.

The structure of the example file Bsp22_01.docx is shown in Figure 22.2. 
At the top level are the three folders _rels, docProps and word and the file [Content_Types].xml.

image::22.2 An extract of the content of a Word document, saved as a ZIP file[]

The word folder contains among other things the files document.xml and styles.xml. 
It is also striking that one folder _rels is on the top level and one in the word sub-folder.

NOTE: The folder structure of a ZIP package is purely virtual and is done for administrative reasons. 
The various parts (files) are grouped hierarchically. 
The relationships between the parts record the .rels files (see also the explanations in the section »Relationships between the parts: rels«).

The XML code of the sample document contained in the XML file `document.xml` (Figure 22.1) is shown in Figure 22.3. 
For a better overview, the file is open in Microsoft Visual Studio Express; Windows will open them in Internet Explorer by default.

image::22.3 The XML code of a simple Word document[]

NOTE: If you are familiar with the HTML markup language, some element names such as "body" and "p" will appear familiar to you. 
This is not surprising, since in both cases the description of "documents" is concerned: Microsoft used known terminology of the same meaning when defining the Word document structures.

And how can you tell that we are dealing with Word Open XML and not with HTML or another markup language? 
The name prefix w: and the associated namespace for wordprocessingml suggest this.

The content of the XML file shows that not all information for the document is stored in this one XML file: The definitions of the formatting are not listed, for example; there is only a reference <w:pStyle w:val="FormatVorlage1" /> before the text of the second paragraph. 
Since the standard formatting is done by the Standard style, it is not listed by name for the first paragraph.

Indeed, the information for an Open XML file is finely structured to ensure optimal content management and the smallest possible file size. 
To keep the file size as small as possible, Word has managed repetitive information centrally and separately from the text, even in the old file formats. 
At that time we only had no insight into the file structure...

NOTE: This is in contrast to the original Word 2003 XML file format: WordProcessingML. 
This was a single XML file that contained all of the information underlying the document, rather than a ZIP package with multiple XML files. 
The Word 2003 version of WordProcessingML has some things in common with the definitions of the namespace http://schemas.openxmlformats.org/wordprocessingml/2006/main of Word Open XML - but they are not exactly identical. 
If you already have a good knowledge of WordProcessingML, this is an advantage, but you need to be careful.

The `styles.xml` file contains the definitions of all styles.

How the files `document.xml` and `styles.xml` are connected is explained in the course of the following discussion in the section »Relationships between the parts: rels«.

On the one hand, it is important to understand the file structure for creating and editing Word documents. 
On the other hand, you also need to know how the application works, because only then you can understand the connections. 
The knowledge gained through the use of Word and its object model definitely pays off when dealing with the Open XML file format!

== The gateway to the Open XML file: [Content_Types.xml]

As can be seen in Figure 22.2, each ZIP package for an Office Open XML document contains a top-level XML file called [Content_Types].xml. 
This file is required and the name is given.

NOTE: For the reader who works exclusively with the Office Open XML SDK, a superficial understanding of this section content is sufficient. 
The tool takes over all the administrative work associated with [Content_Types].xml.

The content of this file is a list of the types of content in the ZIP package; the file content of the sample document is shown in Listing 22.1. 
Each file that is stored in the ZIP package must correspond to one of the types of content listed here, whereby the developer can also define and enter his own in order to integrate his own "third-party" content in the ZIP package. 
All other types of content are ignored by the Office applications, but are available to other applications.

.Listing 22.1 The content types (Content_Types) of the sample document
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">

    <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
    <Default Extension="xml" ContentType="application/xml"/>

    <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformatsofficedocument.wordprocessingml.document.main+xml"/>
    <Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformatsofficedocument.
    wordprocessingml.styles+xml"/>
    <Override PartName="/word/settings.xml" ContentType="application/vnd.openxmlformatsofficedocument.
    wordprocessingml.settings+xml"/>
    <Override PartName="/word/webSettings.xml" ContentType="application/vnd.openxmlformatsofficedocument.
    wordprocessingml.webSettings+xml"/>
    <Override PartName="/word/fontTable.xml" ContentType="application/vnd.openxmlformatsofficedocument.
    wordprocessingml.fontTable+xml"/>
    <Override PartName="/word/theme/theme1.xml" ContentType="application/vnd.openxmlformatsofficedocument.theme+xml"/>
    <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.coreproperties+xml"/>
    <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extendedproperties+xml"/>
</Types>
----

The sub-elements of the top-level `Types` element have either the name `Default` or the name `Override`.

The default elements define the standard content types (indicated by the attribute `ContentType`) and their file extensions (attribute `Extension`), such as `xml` for files that provide the content of an application document (`application/xml`).

After the default entries, there are six override elements in the sample file that point to recognizable parts of the sample document, including the `document.xml` and `styles.xml` files. 
These can easily be found using the values of the `PartName` attribute in Listing 22.1. 
The value of this attribute is a URI and is like a path. 
If you compare the values with the folder structure in Figure 22.2, you can see that this URI refers to the folder structure.

The second attribute, ContentType, also defines the content type of the respective part in the override element. This instruction in an override element tells the Office application that although the file extension is, for example, xml, it is a different type of content than the standard one. 
The application that opens a document knows how to deal with a content type, although different applications might handle the content type differently.

IMPORTANT: Each Office application searches for the specific content type in the `[Content_Types].xml` file. 
If this is not available, the application will not open the document. 
The content type for an Excel workbook is `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml; for a PowerPoint presentation `application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml`; and for a Word document `application/vnd.openxmlformats-officedocument..wordprocessingml.main+xml`.

=== What is a content type

When working with Office Open XML, the question soon arises where the URIs for the ContentType entries come from and how they can be found.

Wikipedia provides a first answer at http://de.wikipedia.org/wiki/Internet_Media_Type [Ms472-K22-03]; the English version at http://en.wikipedia.org/wiki/Internet_media_type [Ms472-K22-04] provides more detailed information. 
The article describes the common, open standard for defining content types in Internet traffic; Office Open XML uses this standard.

The first segment of all URIs in Listing 22.1 is "application". 
This term indicates that each part of this type of content provides information for an application. 
The following designation "vnd" stands for "vendor" (as much as provider) and indicates that it is a type of content for a software manufacturer's application. 
In this case, the other information in the URI comes from the manufacturer and tells its application what type of content is to be expected.

The URI `application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml` is therefore the instruction for the content type of a document in the vocabulary WordProcessingML for an Office document of the file format Office Open XML. 
The application (Word) thus knows that such parts can be expected in the ZIP package and that one of these parts is in the path `\word`.

When opening an Open XML file, Microsoft Office applications look for such entries to ensure that it is a file for this application. 
For example, Internet Explorer recognizes that a `.docx` file in Word and an `.xlsx` file in Excel.

Anyone working with the Open XML SDK presented in a following chapter does not need to know how to deal with content types in detail. 
However, developers who use other tools to work with Open XML documents do. 
The SDK does this work for us.

Of course, this raises the question of where the developer can find a list of the types of content? 
Unfortunately, the documentation does not provide a clear list of all types of content. 
They are scattered in the documents for the ECMA standard and the information for the office implementation of this standard. 
The most basic types of content can be found in Part 1 (Fundamentals and Markup Language Reference) of the ISO/IEC 29500:2008 standard documents. 
Extended content types are also available in the "[MS-OI29500]: Office Implementation Information for ISO/IEC 29500 Standard Compliance".

ONLINE: We have summarized information from these sources in the Excel workbook `OpenXML_Types.xlsx`, which is available in the download archive for the book in the `\Supplements\Kap22` folder.

== Parts and their naming

The term "part" represents a file stored in the ZIP package. 
An Office Open XML file consists of a ZIP package with several parts, which are arranged hierarchically. 
In the present example, `document.xml` and `styles.xml` form parts of the ZIP package `Bsp22_01.docx`. 
The Office applications name the individual parts of a ZIP package that represents a document of the application with names according to a certain pattern: 
For example, the XML file for a Word document always has the name `document.xml`, that for an Excel file Name `workbook.xml`.

The developer may give individual parts different names than those used by Office. 
The Office document remains valid and can be opened by the target application. 
The decisive factor is the content type assigned in `[Content_Types].xml`, not the name.

IMPORTANT: Please note the following: It is not enough to simply give the part a different name. 
The entries for the content type in `_rels/.rels` and in `[Content_Types].xml` must also be adjusted accordingly. 
Otherwise the Office application considers the document damaged and cannot open it.

However, it is possible for the Office application to save the file names in the ZIP package when the document is saved again.

This should always be kept in mind during programming: you cannot rely on the file name! Parts must be found using content types and relationship types, which are described in more detail in the following section.

NOTE: Parts play an important role when dealing with Open XML documents. 
However, anyone who works with the Open XML SDK does not have to worry about their naming, since the tool generalizes this information. 
However, when working with documents that were not created by Microsoft Word, a confrontation with unknown naming of parts cannot be excluded. 
So you should be aware of this possibility.

=== New terminology

Most of the documentation sources for Open XML are in English. 
The following is a comparison of the terminology in both languages.

.22.1 New terminology of the section »The gateway to the Open XML file: [Content_Types.xml]«
[%header, cols=3*]
|===
|German Term
|English Term
|Short Description

|ZIP-Paket
|Zip package
|A collection of files that are stored in a ZIP file according to the ZIP standard

|Inhaltsart
|ContentType
|The type of content of a file included in the ZIP package

|Teil
|Part
|A file included in the ZIP package
|===

== Relationships between the parts: rels

Although the entry file `[Content_Types].xml` contains "path details" in the form of URIs that point to files in the ZIP package, these are not used by the Office application to address individual parts. 
Several parts can be of the same content type without being listed individually in `[Content_Types].xml`. 
The actual relationships (relationships) between the individual parts of a ZIP package are managed by `.rels` files, which are located in several `_rels` subfolders (a subfolder for each folder with files that maintain relationships).

NOTE: The Open XML SDK developer does not have to master every detail of managing relationships. 
However, a good understanding of the concepts in this section is a prerequisite for successful application. 
Relationships provide the necessary information for the hierarchical structure of a document. 
The individual parts with which the code is to work can only be addressed via them.

As mentioned in the section "Parts and their naming", it cannot be assumed that a certain part always has the same file name. 
A part should not be found using the file name.

Image::22.4 The content of a ZIP package is shown as ramifications

Most developers are used to working with object-oriented models and going through hierarchies of listings and their objects when an object cannot be clearly addressed using an index value. 
For example, it is done with file folders and files if you want to use the Dir command to drag through folders.

This procedure would not be particularly efficient for the creation and management of Open XML documents. 
Although the contents of a ZIP package are usually displayed graphically in a folder structure with subfolders and files, these folders do not really exist. 
The content could just as well be represented as a branching of nodes, as can be seen in Figure 22.4.

It would be desirable to be able to address files that are to be worked with directly. 
This would require a system that enables a direct connection to every node, similar to working with XPath. 
Exactly this service is fulfilled by the entries in the `.rels` files, which are always located in a `_rels` folder on a hierarchical level.

The starting point for researching the content of an Open XML document is the `.rels` file in the `_rels` folder of the first hierarchical level, the content of which is shown in Listing 22.2 for the sample document.

A `.rels` file contains a Relationships element with multiple relationship sub-elements. 
Each of these sub-elements has the three attributes `Target`, `Type` and `Id`. 
The value of the attribute `Id` uniquely identifies a part within the hierarchy level. 
`Type` identifies the type of the relationship. 
`Target` provides the path specification (the URI) to the file of the relationship type.

.Listign 22.2 The contents of the top-level `.rels` file
----
<?xml version="1.0" encoding="UTF-8" standalone="true"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
    <Relationship Target="docProps/app.xml"
        Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extendedproperties"
        Id="rId3"/>
    <Relationship Target="docProps/core.xml"
        Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/coreproperties"
        Id="rId2"/>
    <Relationship Target="word/document.xml"
        Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument"
        Id="rId1"/>
</Relationships>
----

If you want to work with the document, a relationship of the type http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument is searched for in the top level of the ZIP package. 
If such a relationship exists, the file can be accessed directly via the path (URI) specified in Target - in this case `word/document.xml` - without having to search for it in all hierarchy levels.

The XML code of the document is now available, as shown in Figure 22.3. 
We are interested in formatting the second paragraph. 
The Word Open XML code for this can be seen again in Listing 22.3. 
Its formatting is determined by the format template »FormatVorlage1«.

----
<w:p>
    <w:pPr>
        <w:pStyle w:val="FormatVorlage1"/>
    </w:pPr>
    <w:r>
        <w:t>Text formatiert mit der Formatvorlage &gt;&gt;FormatVorlage 1&gt;&gt;.</w:t>
    </w:r>
</w:p>
----

Because the definitions of the styles are managed in another file, the next stop is the `_rels` subfolder of the current folder `word`. 
In this example, this contains a single `.rels` file: `document.rels.xml`, the content of which is shown in Listing 22.4. 
As the name suggests, we are dealing with the relationships of the document part.

TIP: Under certain circumstances there may be several `.rels` files in the `_rels` folders of the lower hierarchy levels. 
The `.rels` file for an XML file always has the same name as the file in which the relationships exist, as well as the `.rels.xml` file extension. 
The top level of the Open XML file has no name, which is why the file is simply called `.rels`.

.Listing 22.4 The relationships in `document.xml.rels`
----
<?xml version="1.0" encoding="UTF-8" standalone="true"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
    <Relationship Target="webSettings.xml"
        Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/webSettings"
        Id="rId3"/>
    <Relationship Target="settings.xml"
        Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings"
        Id="rId2"/>
    <Relationship Target="styles.xml"
        Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles"
        Id="rId1"/>
    <Relationship Target="theme/theme1.xml"
        Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme"
        Id="rId5"/>
    <Relationship Target="fontTable.xml"
        Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/fontTable"
        Id="rId4"/>
</Relationships>
----

The Word application knows that it has to look for styles in a http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles file. 
It cannot rely on a specific name, as explained in the section "Parts and their Names". 
Here too, the Target attribute supplies the URI for the file with the desired information, in this case `styles.xml`. 
Since the `styles.xml` file is in the same folder as the `document.xml` file, the URI does not require folder information. 
URIs are relative paths.

An excerpt from the `styles.xml` file is shown in Listing 22.5. 
To find the definition of the formatting of the second paragraph, we needed the value of the `w:val` attribute in the `w:pStyle` element of the `document.xml` file (Listing 22.3):Formatvorlage1.
After this, the `w:styleId` attribute of part style elements searched. 
The sub-elements describe the individual formatting properties of the style.

.Listing 22.5: The content of the `styles.xml` file
----
    <w:style w:styleId="Standard" w:default="1" w:type="paragraph">
        <w:name w:val="Normal"/>
        <w:qFormat/>
        <w:rPr>
            <w:lang w:val="de-CH"/>
        </w:rPr>
    </w:style>
    <w:style w:styleId="Absatz-Standardschriftart" w:default="1" w:type="character">
        <w:name w:val="Default Paragraph Font"/>
        <w:uiPriority w:val="1"/>
        <w:semiHidden/>
        <w:unhideWhenUsed/>
    </w:style>
    <w:style w:styleId="FormatVorlage1" w:type="paragraph" w:customStyle="1">
        <w:name w:val="FormatVorlage 1"/>
        <w:basedOn w:val="Standard"/>
        <w:rPr>
            <w:rFonts w:hAnsi="Times New Roman" w:ascii="Times New Roman"/>
            <w:b/>
            <w:caps/>
            <w:color w:val="AEAAAA" w:themeShade="BF" w:themeColor="background2"/>
            <w:sz w:val="18"/>
        </w:rPr>
    </w:style>
</w:styles>
----

Figure 22.5 illustrates how relationships work. 
They make it possible to address the parts of the ZIP package directly, instead of having to search through the individual nodes of the hierarchy.

image::22.5 Find parts of the ZIP package using relationships (rels)

=== Documentation about relationship types

As for the content types, the information for the different relationship types is listed in several places in the documentation. 
The most basic types of relationships are in Part 1 (Fundamentals and Markup Language Reference) of the ISO/IEC 29500:2008 standard documents. 
Extended relationship types are also available in "[MS-OI29500]: Office Implementation Information for ISO/IEC 29500 Standard Compliance".

ONLINE: We have summarized information from these sources in the Excel workbook `OpenXML_Types.xlsx`, which is available in the download archive for the book in the `\Supplements\Kap22` folder.

=== Implicit and explicit relationships

So far we have only dealt with relationships that are unique: In a Word document, only one main document part (`document.xml`) and one part for the definitions of the styles (`styles.xml`) may appear. 
Consequently, it can be in the `.rels` files for these parts give only one entry for the corresponding relationship type.

However, there are other types of relationships that can occur multiple times, such as for headers and footers. 
As you know, a Word document can have up to three different headers and footers for each section if the options for a first page and for different even and odd pages are activated. 
Each has its own XML file in a ZIP package, as shown in Figure 22.6.

image: 22.6 A Word Open XML document with headers

ONLINE: The sample file `Bsp22_02.docx` is located in the download archive for the book in the `\Examples\Kap22` folder

As is known, headers and footers are defined in the section changes. 
Consequently, they are in `document.xml` under the element that defines the section properties: `w:sectPr`, as `w:headerReference` or `w:footerReference` elements (Figure 22.7).

image 22.7: The `document.xml` file with headers for the first and normal pages.

The attribute `r:id` therefore indicates which identity relationship points to the corresponding part in the ZIP package. 
So we can look up the corresponding part.

Relationships between `document.xml` are managed in `word/_rels/document.xml.rels`, the content of which is shown in Listing 22.6 for this example. 
There you can see that the definition for the header of the first page is in `header2.xml` (Id = rId7), while `header1.xml` (Id = rId6) is responsible for the content of the remaining pages.

.Listing 22.6 Contents of the `document.xml.rels` file for the header example
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
    <Relationship Id="rId8" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/fontTable"
        Target="fontTable.xml"/>
    <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/webSettings"
        Target="webSettings.xml"/>
    <Relationship Id="rId7" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/header"
        Target="header2.xml"/>
    <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings"
        Target="settings.xml"/>
    <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles"
        Target="styles.xml"/>
    <Relationship Id="rId6" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/header"
        Target="header1.xml"/>
    <Relationship Id="rId5" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/endnotes"
        Target="endnotes.xml"/>
    <Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footnotes"
        Target="footnotes.xml"/>
    <Relationship Id="rId9" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme"
        Target="theme/theme1.xml"/>
</Relationships>
----

If an `ID` value is required to determine the uniqueness of a part, we speak of an explicit relationship. 
If the relationship is unique based on the relationship type, because only a part of this type is allowed, we are dealing with an implicit relationship.

IMPORTANT: This concept is important for the technical handling of Open XML files, regardless of whether you are working with the Open XML SDK or another tool.

NOTE: The ISO/IEC 29500:2008 standard documents contain information on the number of parts that are permitted in a ZIP package.

=== Internal and external relationships

Most relationships in an Open XML package point to targets within the document, as in the examples listed.

Destinations outside the file are also possible, such as linked mail merge data sources, subdocuments of a Word master document, images or Excel workbooks. 
In these cases, these are external relationships.

=== Allowed relationships

There are parts that must be present in a particular Word document, such as `document.xml`. 
Without this part, the document would have no content; Word couldn't open it. 
Other parts are optional: a document can contain headers and footers, but does not have to.

Relationships always occur in pairs. 
A source refers to a target part. 
Most of the time, the relationship is one-way. 
An image, for example, cannot serve as the target type of a relationship for the document; only the other way round is possible. 
Many parts, like those that describe formatting, can only serve as targets and not as sources.

There is a relationship type for each combination of parts. 
We are talking about required, allowed and illicit relationship types.

The Office Open XML standard defines the permitted relationship types for the individual applications.

=== New terminology

Table 22.2 summarizes and briefly explains the terms presented in this section.

Table 22.2: New terminology of the section »Relationships between the parts: rels«
[%header, cols=3*]
|====
|German Term
|English Term
|Short Description

|Beziehungen
|Relationships
|Describe the relationships between the parts of a ZIP package

|Beziehungstyp
|relationship type
|A URI that clearly describes the relationship type. 

|Ziel
|target
|The part of the ZIP package that corresponds to the specified relationship type

|Quelle
|source
|The part of the ZIP package that contains relationships to other parts with additional content

|.rels-Datei
|.rels file
|Manages a source's relationships and lists the relationship types for the source with their goals

|Explizite Beziehung
|explicit relationship
|This is the case if several target files of the same relationship type are allowed in the ZIP package

|Implizite Beziehung
|implicit relationship
|This is the case if only one target file can exist in the ZIP package for a relationship type

|Interne Beziehung
|internal relationship
|Source and target parts are in the same Open XML file

|Externe Beziehung
|external relationship
|The target part is in another file

|====

== Practical application: replace a part

Although the insight into the interior of an office document can be interesting, it does not help the developer: he must be able to do something with this information. 
In this section we present a small example of the possibilities that Open XML offers developers. 
Without code and without starting the Word application, the appearance of the document from Figure 22.8 is converted into the document shown in Figure 22.9.

image::22.8 The document template in the old corporate identity

image::22.9 The new logo and the changed font formatting in the new corporate identity

ONLINE: The sample files `Bsp22_03.dotx` and `Bsp22_04.dotx` can be found in the download archive for the book in the `\Examples\Kap22` folder

Almost everyone who works in the same company for a long time has seen a change in corporate identity. 
For example, the logo as well as the fonts and possibly also the colors that can be used in documents are changed.

This process is partly taken into account with the »designs« functionality. 
However, it often happens that the document templates for letterheads and other document types have to be dapted. This work can be extremely tedious, even if macros are used to support it.

=== Programming environments for working with Office Open XML

=== Online resources for Office Open XML

An overview of the file format in German can be found in Wikipedia: http://de.wikipedia.org/wiki/Office_Open_XML [Ms472-K22-07].

However, most documentation sources are in the English language. 
Below is an overview.

*ISO-Standard*

The main documents for the ISO/IEC 29500:2008 standard are available at http://standards.iso.org/ittf/PubliclyAvailableStandards/index.html [Ms472-K22-08]. 
These are reference works for all aspects of Office Open XML. 
The ISO/IEC 29500:2008 standard documents include four main documents with appendices, as follows:
- The ISO/IEC 29500:2008 standard documents include four main documents with appendices, as follows:

Contains definitions of conformity and reference material, including XML schemas for the XML document markup languages. 
This part comprises more than 5,500 pages.

- Part 2 (Open Packaging Convention)

(As presented in this section.) Describes the OPC, core properties, and other package-related items, such as handling digital signatures and miniatures. 
It provides the XML schemas for the OPC. 
This part has more than 1,000 pages.

- Part 3 (Markup Compatibility and Extensibility)

Describes the expansion options and comprises approximately 40 pages.

- Part 4 (Transitional Migration Features)

Describes parts from previous versions that are still supported for backward compatibility, such as VML (Vector Markup Language, two-dimensional graphics). 
It lists the differences between »ISO/IEC 29500: 2008« and »ECMA-376 1st edition«.

Where is the right entry point so that you don't lose track of so much information? 
For starters, the first part is the most important. 
We recommend “Section 8 - Overview” of ISO/IEC 29500-1 “Fundamentals and Markup Language Reference” as an introduction.

Afterwards, it makes sense to skim over the table of contents of the four main documents and to keep an eye out for the topics that are relevant to the task at hand.

Although this documentation may seem overwhelming at first, it contains extensive explanatory texts and helpful examples.

==== additional Information

The document `Primer.docx`, which is part of »ECMA-376 1st Edition Part 3«, offers a good introduction to the topic of Office Open XML. 
It can be downloaded as a Word document or PDF file from http://www.ecma-international.org/publications/standards/Ecma-376.htm [Ms472-K22-09].

The namespaces and schemas are fully listed, with information and examples, at http://www.schemacentral.com/sc/ooxml/s-wml.xsd.html [Ms472-K22-13]. 
Information, documentation, examples and discussion forums can be found on OpenXMLDeveloper.org.

Information for various programming languages such as Java, C++, Linux and Mac can also be called up here.

==== Forums

The forums on OpenXMLDeveloper.org cover many topics and programming languages. 
These are used by numerous Open XML developers. 
The MSDN's English-language forums include the Open XML SDK forum, which specializes in this tool: http://social.msdn.microsoft.com/Forums/office/en-us/home?forum=oxmlsdk [Ms472-K22-14]. 
There is also a forum for the Microsoft implementations of the Open XML file formats: http://social.msdn.microsoft.com/Forums/en-us/home?forum=os_openXMLecma [Ms472-K22-15].

== Summary